# Build Multitarget Application & Deploy it to Cloud Foundry
name: Teste pipeline main

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ main ]